version: "3"

services:
  rails:
    build: .
    image: calvincaulfield/profile
    ports:
      - 3002:3002
    command: ./start_docker.sh
    restart: always
    environment:
      - RAILS_ENV=production
      - DB_HOST
      - DB_USER
      - DB_PORT
      - DB_PASSWD
      - PROFILE_PORT
      - SECRET_KEY_BASE
      - RAILS_SERVE_STATIC_FILES
    network_mode: host
